FROM node:13 as builder

# Update container
RUN apt-get update

# Tiny allows to gracefully stop node process
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

# Set environement to devellopment
ENV NODE_ENV=devellopment

# Install prisma for graphql
RUN yarn global add prisma

# Create node directory 
WORKDIR /node

# Copy npm dependencies
COPY package*.json yarn.lock* ./

# Create app directory to contain the app and set permision for node user
RUN mkdir app && chown -R node:node .

# Change the user to be node
USER node

# Install dependencies
RUN yarn install

# Change for app directory
WORKDIR /node/app

# Copy existing local files into container, and set permission to node user
COPY --chown=node:node  . .

# Tiny entrypoint
ENTRYPOINT ["/tini", "--"]

CMD [ "yarn", "dev" ]