FROM node:latest as builder

# Install yarn 
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update \
  && apt-get install -y yarn

# Install prisma for graphql
RUN yarn global add prisma

# Create directory 
RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app

# Install npm dependencies
COPY package.json package-lock.json* yarn.lock* /home/nodejs/app/
RUN yarn install

# Copy existing local files into container, and set permission
COPY . /home/nodejs/app

EXPOSE 5000

CMD [ "yarn", "dev" ]